Train:
  model: clinicalbert # bert or clinicalbert
  finetune: head # head or full
  lr: 0.00001 # 1e-5
  epochs: 1
  batch: 8
  adapter: False # True or False
  adapter_method: SeqBnConfig # SeqBnConfig,DoubleSeqBnConfig,Houlsby need to change to new adapters : seq_bn ,seq_bn,double_seq_bn  - https://docs.adapterhub.ml/overview.html
  reduction_factor: 64
  hd: cpu # intel or arm
  wandb: False # True or False
  wandb_api_key: 58b1d32f1860dd69955c751444efc8d61a153182 #set your own api key here

data:
  i2b2: beth_and_partners # all or beth_and_partners
  frac: 0.1
