Train:
  task: ast #ner or ast
  model: bert # bert or clinicalbert
  finetune: head # head or full
  lr: 0.00001 # 1e-5
  epochs: 2
  batch: 16
  weight_decay : 0.002
  adapter: False # True or False
  adapter_method: SeqBnConfig # SeqBnConfig,DoubleSeqBnConfig,Houlsby need to change to new adapters : seq_bn ,seq_bn,double_seq_bn  - https://docs.adapterhub.ml/overview.html
  reduction_factor: 64
  logging_steps: 500
  hd: cpu # intel or arm
  wandb: False # True or False
  wandb_api_key: 271574447bdb191e432e3500768bb709afc7d7d3 #set your own api key here #Niharika : 271574447bdb191e432e3500768bb709afc7d7d3

data:
  i2b2: all # all or beth_and_partners
  frac: 0.1
