Train:
  model: clinicalbert # bert or clinicalbert
  finetune: full # head or full
  lr: 0.00001
  epochs: 1
  batch: 8
  adapter: False # True or False
  adapter_method: Houlsby, # Pfeiffer,Houlsby need to change to new adapters : seq_bn ,seq_bn,double_seq_bn  - https://docs.adapterhub.ml/overview.html
  hd: intel # intel or arm

data:
  i2b2: all # all or beth_and_partners
  frac: 0.01
