name: clinical-adapter
channels:
- defaults
- pytorch
- conda-forge
dependencies:
- python=3.8
- numpy
- pandas
- matplotlib
- scikit-learn
- pytorch
- torchvision
- pip
- pip:
  - spacy
  - ipykernel
  - evaluate
  - datasets
  - accelerate
  - https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_ner_bc5cdr_md-0.4.0.tar.gz
  - adapter-transformers

